name: ml_phase_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - h5py
  - pytorch
  - torchvision
  - torchaudio
  - scikit-learn
  - pip
  - pip:
    - mdtraj
